site_name: Test Site
site_url: https://aysecanuenal.github.io/test-site
theme:
  name: material
  palette:
  primary: 'orange'  

  icon:
    logo: material/glass-cocktail    

nav:
  - Home: index.md
  - About: about.md    
